import { createFileRoute, Link } from "@tanstack/react-router";
import { Logo } from "@/components/site/Logo";
import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";

export const Route = createFileRoute("/terms")({
  head: () => ({ meta: [{ title: "Terms of Service — Medier AI" }] }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <header className="container mx-auto max-w-4xl px-5 py-5 flex items-center justify-between">
        <Logo />
        <Link to="/auth">
          <Button variant="ghost" size="sm" className="text-muted-foreground">
            <ArrowLeft className="size-4 mr-1" /> Back
          </Button>
        </Link>
      </header>

      <main className="container mx-auto max-w-4xl px-5 py-12 space-y-8">
        <div>
          <h1 className="font-display text-4xl mb-2">Terms of Service</h1>
          <p className="text-muted-foreground text-sm">Last updated: June 2026</p>
        </div>

        <Section title="1. Acceptance of Terms">
          By accessing or using Medier AI ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service. You must be at least 18 years of age to use Medier AI.
        </Section>

        <Section title="2. Description of Service">
          Medier AI is an AI-powered marketing content generation platform designed for hospitality businesses in Greece. The Service generates marketing packs including social media content, listing descriptions, email templates, ad copy, and Google My Business content.
        </Section>

        <Section title="3. User Accounts">
          You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to notify us immediately at support.medierai@gmail.com of any unauthorized use of your account. We reserve the right to terminate accounts that violate these terms.
        </Section>

        <Section title="4. Subscription Plans and Payments">
          Medier AI offers the following subscription plans:
          <ul className="list-disc pl-6 mt-3 space-y-1 text-sm text-foreground/80">
            <li><strong>Free:</strong> 3 packs total, no credit card required</li>
            <li><strong>Starter:</strong> €25/month or €240/year — 10 packs/month</li>
            <li><strong>Pro:</strong> €49/month or €468/year — 25 packs/month</li>
            <li><strong>Max:</strong> €70/month — Unlimited packs</li>
          </ul>
          <p className="mt-3">Payments are processed securely by Stripe. By subscribing, you authorize us to charge your payment method on a recurring basis. All prices include applicable taxes.</p>
        </Section>

        <Section title="5. Cancellation and Refunds">
          You may cancel your subscription at any time through your account settings. Upon cancellation, you will retain access to your plan's features until the end of the current billing period. We do not offer refunds for partial billing periods. If you believe you are entitled to a refund, please contact us at support.medierai@gmail.com within 7 days of the charge.
        </Section>

        <Section title="6. Acceptable Use">
          You agree not to use Medier AI to generate content that is illegal, defamatory, fraudulent, or infringes on third-party intellectual property rights. You are solely responsible for the content you generate and how you use it. We reserve the right to suspend or terminate accounts that misuse the Service.
        </Section>

        <Section title="7. Intellectual Property">
          The content generated by Medier AI is provided for your business use. You retain ownership of content you generate. Medier AI retains ownership of the platform, its design, algorithms, and underlying technology. You may not copy, reverse-engineer, or redistribute the Service itself.
        </Section>

        <Section title="8. AI-Generated Content Disclaimer">
          Content generated by Medier AI is created by artificial intelligence and may require review and editing before use. We do not guarantee the accuracy, completeness, or suitability of generated content for any specific purpose. Always review AI-generated content before publishing.
        </Section>

        <Section title="9. Limitation of Liability">
          To the maximum extent permitted by Greek and EU law, Medier AI shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service. Our total liability to you shall not exceed the amount you paid us in the 3 months preceding the claim.
        </Section>

        <Section title="10. Changes to Terms">
          We reserve the right to modify these Terms at any time. We will notify users of significant changes via email. Continued use of the Service after changes constitutes acceptance of the new Terms.
        </Section>

        <Section title="11. Governing Law">
          These Terms are governed by the laws of Greece and the European Union. Any disputes shall be subject to the exclusive jurisdiction of the courts of Greece.
        </Section>

        <Section title="12. Contact">
          For any questions regarding these Terms, please contact us at{" "}
          <a href="mailto:support.medierai@gmail.com" className="text-gold hover:underline">
            support.medierai@gmail.com
          </a>
        </Section>
      </main>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="space-y-3">
      <h2 className="font-display text-xl text-gold">{title}</h2>
      <div className="text-foreground/80 leading-relaxed text-sm">{children}</div>
    </div>
  );
}